#!/usr/bin/env python3
"""portfolio — broker- and instrument-agnostic lot register and sell planner.

Command surface is specified in specs/005-portfolio-tax-pack/contracts/cli.md.

    python3 main.py validate
    python3 main.py report  [--ticker T] [--as-of D] [--spot P] [--fx R] [--format F]
    python3 main.py import  --file F --profile P [--dry-run]
    python3 main.py share   --profile P [--out PATH] [--preview]
    python3 main.py migrate --from DIR [--dry-run]

Exit codes: 0 ok · 1 usage/validation failure · 2 refused.

Every path this writes is a symlink into data/portfolio/ (ADR 0019); the writes
go through portfolio.store, which resolves the link first so the symlink is
never replaced by a real file. Nothing here writes inside packs/.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from portfolio import disclosure as disclosurelib
from portfolio import document as doclib
from portfolio import importer as importlib_
from portfolio import page as pagelib
from portfolio import profiles as profilelib
from portfolio import ratings as ratinglib
from portfolio import store
from portfolio.rules import RateTable, Rates
from portfolio.store import DataError

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"                     # symlinks into data/portfolio/
REGISTER = DATA / "register.yaml"
FX_RATES = DATA / "fx-rates.yaml"
RULES = DATA / "rules.yaml"
DISCLOSURE = DATA / "disclosure.yaml"
PAGE_OUT = DATA / "explorer.html"
DOC_OUT = DATA / "explorer-document.json"
TEMPLATE = HERE / "templates" / "explorer.html"
PROFILE_DIR = HERE / "profiles"

REGISTER_HEADER = """\
# data/portfolio/register.yaml — open lots and closed disposals.
#
# PUBLISHED CROSS-PACK CONTRACT (packs/portfolio/schemas/lot-register.schema.json).
# The portfolio pack is its only writer; other packs read it.
#
# Regenerated by `portfolio import`. Hand edits are expected and safe — run
# `portfolio validate` after. Derived values (maturity, mature) are NOT stored:
# they come from acq_date plus the rules file, so they cannot drift from it.
"""


# ---------- shared loading ---------------------------------------------------
def load_all(need_disclosure: bool = False):
    register = store.load_validated(REGISTER, "lot-register.schema.json",
                                    "register.yaml")
    rules = store.load_yaml(RULES, "rules.yaml")
    fx = RateTable(store.load_yaml(FX_RATES, "fx-rates.yaml"))
    profiles = None
    if need_disclosure:
        profiles = store.load_validated(DISCLOSURE,
                                        "disclosure-profile.schema.json",
                                        "disclosure.yaml")
    return register, rules, fx, profiles


def spot_fx(register, rules, override=None):
    """The reporting-currency rate to value at. Register-level, overridable."""
    if override is not None:
        return override
    return register.get("fx", {}).get("spot") or rules.get("default_fx") or 1.0


# ---------- validate ---------------------------------------------------------
def cmd_validate(args) -> int:
    problems: list[str] = []

    for path, schema, label in (
        (REGISTER, "lot-register.schema.json", "register.yaml"),
        (DISCLOSURE, "disclosure-profile.schema.json", "disclosure.yaml"),
    ):
        try:
            data = store.load_yaml(path, label)
            problems += store.validate_against(data, schema, label)
        except DataError as exc:
            problems.append(str(exc))

    try:
        rules = store.load_yaml(RULES, "rules.yaml")
        problems += [f"rules.yaml: {p}" for p in
                     ratinglib.validate_definitions(rules.get("lot_ratings", []))]
        Rates(rules)
    except (DataError, KeyError, ValueError) as exc:
        problems.append(f"rules.yaml: {exc}")

    for profile_path in sorted(PROFILE_DIR.glob("*.yaml")):
        label = f"profiles/{profile_path.name}"
        try:
            profile = store.load_yaml(profile_path, label)
            problems += store.validate_against(
                profile, "broker-profile.schema.json", label)
            problems += profilelib.validate_profile(profile)
        except DataError as exc:
            problems.append(str(exc))

    if args.strict:
        try:
            register = store.load_yaml(REGISTER, "register.yaml")
            for ticker, position in (register.get("positions") or {}).items():
                for lot in position.get("lots", []):
                    for flag in lot.get("flags", []) or []:
                        problems.append(
                            f"--strict: {ticker} lot {lot.get('id')} carries "
                            f"{flag['code']}: {flag['note']}")
        except DataError:
            pass

    if problems:
        print(f"{len(problems)} problem(s):\n", file=sys.stderr)
        for problem in problems:
            print(f"  • {problem}", file=sys.stderr)
        return 1
    print("OK — every data file valid.")
    return 0


# ---------- report -----------------------------------------------------------
def cmd_report(args) -> int:
    register, rules, _, _ = load_all()
    when = (datetime.strptime(args.as_of, "%Y-%m-%d").date()
            if args.as_of else date.today())
    fx = spot_fx(register, rules, args.fx)

    document = doclib.build(register, rules, when=when, fx=fx,
                            ticker=args.ticker, spot_override=args.spot)

    if args.format == "json":
        target = store.save_json(DOC_OUT, document)
        print(f"wrote {target}")
        return 0

    if args.format == "text":
        print(render_text(document))
        return 0

    doc_target = store.save_json(DOC_OUT, document)
    html = pagelib.render(TEMPLATE, document)
    page_target = store.save_text(PAGE_OUT, html)
    print(f"wrote {page_target}  ({len(html):,} bytes, self-contained)")
    print(f"wrote {doc_target}")
    summary = doclib.summarise(document)
    print(f"  {summary['instruments']} instrument(s), {summary['lots']} open "
          f"lot(s), {summary['shares']:g} shares"
          + (f", {summary['unpriced']} unpriced" if summary["unpriced"] else ""))
    if document["flags_present"]:
        print("  ⚠ some figures rest on unverified inputs — see the page, or "
              "run `validate --strict`")
    return 0


def render_text(document: dict) -> str:
    lines = [f"# portfolio — {document['valuation_date']} "
             f"(generated {document['generated_at']})",
             f"STCG {document['rules']['stcg']:.2%} · "
             f"LTCG {document['rules']['ltcg']:.2%} · "
             f"maturity {document['rules']['ltcg_months']} months", ""]
    for position in document["positions"]:
        if not position["priced"]:
            lines.append(f"{position['ticker']}: UNPRICED — "
                         f"{len(position['lots'])} lot(s), excluded from totals")
            continue
        lines.append(f"{position['ticker']}  spot {position['spot']} · "
                     f"fx {position['fx']}")
        for lot in position["lots"]:
            be = f"{lot['breakeven']:>9.2f}" if "breakeven" in lot else "        —"
            cu = f"{lot['cushion']:+.1%}" if "cushion" in lot else "     —"
            flag = " ⚠" if lot.get("flags") else ""
            lines.append(f"  {lot['id']:<16} {lot['funding']:<7} "
                         f"{lot['qty']:>9g} {lot['cb']:>9.2f} "
                         f"{lot['mat']} {lot['rating']:<12} {be} {cu}{flag}")
        lines.append("")
    return "\n".join(lines)


# ---------- import -----------------------------------------------------------
def cmd_import(args) -> int:
    register, rules, fx_table, _ = load_all()
    profile_path = PROFILE_DIR / f"{args.profile}.yaml"
    if not profile_path.exists():
        available = ", ".join(sorted(p.stem for p in PROFILE_DIR.glob("*.yaml")))
        print(f"no profile {args.profile!r}. Available: {available}. "
              f"Adding a broker is a new profile file, not a code change.",
              file=sys.stderr)
        return 1

    profile = store.load_validated(profile_path, "broker-profile.schema.json",
                                   f"profiles/{profile_path.name}")
    problems = profilelib.validate_profile(profile)
    if problems:
        for problem in problems:
            print(f"  • {problem}", file=sys.stderr)
        return 1

    try:
        batch = importlib_.run(Path(args.file), profile, register, rules,
                               fx_table, dry_run=args.dry_run,
                               allow_duplicate_rows=args.allow_duplicate_rows)
    except importlib_.ImportRefused as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2

    print(importlib_.format_batch(batch, args.dry_run))

    if not args.dry_run:
        target = store.save_yaml(REGISTER, register, REGISTER_HEADER)
        print(f"\nwrote {target}")
    else:
        print("\nNothing written. Re-run without --dry-run to apply.")
    return 0


# ---------- share ------------------------------------------------------------
def cmd_share(args) -> int:
    register, rules, _, profiles = load_all(need_disclosure=True)
    available = profiles.get("profiles", {})
    if args.profile not in available:
        print(f"no disclosure profile {args.profile!r}. Available: "
              f"{', '.join(sorted(available))}", file=sys.stderr)
        return 1

    profile = dict(available[args.profile], _name=args.profile)
    fx = spot_fx(register, rules)
    document = doclib.build(register, rules, when=date.today(), fx=fx)

    if not profile.get("withhold"):
        print("This produces a FULL-DISCLOSURE copy. It will contain:")
        print("  • every lot, its quantity, cost basis and acquisition date")
        print("  • every disposal, its price and realised gain")
        print("  • current market value and tax figures")
        if not sys.stdin.isatty():
            print("Refusing on a non-interactive run — a full copy is never "
                  "produced by default (FR-050).", file=sys.stderr)
            return 2
        if input("Type 'yes' to produce it: ").strip().lower() != "yes":
            print("Aborted. Nothing produced.")
            return 0

    try:
        redacted = disclosurelib.apply(document, profile,
                                       profiles.get("derivations", []))
    except disclosurelib.DisclosureRefused as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 2

    # Resolve through a declared FILE, not the directory: `data/` inside the
    # pack is a real directory holding symlinks, so resolving it would put the
    # shared copy inside packs/ — data in the pack, which Principle II forbids
    # and the write sandbox denies. A declared file's target is in data/<pack>/.
    out = Path(args.out) if args.out else (
        store.resolve_target(PAGE_OUT).parent / "shared" /
        f"{args.profile}-{date.today().isoformat()}.html")
    out.parent.mkdir(parents=True, exist_ok=True)
    html = pagelib.render(TEMPLATE, redacted)
    out.write_text(html)

    print(f"wrote {out}")
    if redacted["withheld"]:
        print(f"  withheld: {', '.join(redacted['withheld'])}")
        print(f"  verified absent from the delivered bytes, not merely hidden")
    if args.preview:
        print(f"  preview: open {out} — this is exactly what the recipient sees")
    return 0


# ---------- migrate ----------------------------------------------------------
def cmd_migrate(args) -> int:
    src = Path(args.source).expanduser()
    holdings_path = src / "data" / "holdings.yaml"
    if not holdings_path.exists():
        print(f"no holdings.yaml under {src}", file=sys.stderr)
        return 1

    raw_text = holdings_path.read_text()
    comments = [line.strip() for line in raw_text.splitlines()
                if line.strip().startswith("#") and len(line.strip()) > 3]

    import yaml
    old = yaml.safe_load(raw_text)

    register = {
        "contract_version": "1.0.0",
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "reporting_currency": "INR",
        "funding": {k: {"label": v["label"],
                        "own_money": ("none" if v.get("outlay") == "none"
                                      else "partial" if v.get("own_money") == "partial"
                                      else "full"),
                        "desc": v["desc"]}
                    for k, v in (old.get("funding") or {}).items()},
        "positions": {},
    }

    for ticker, position in (old.get("positions") or {}).items():
        market = (old.get("market") or {}).get(ticker, {})
        entry = {"broker": position.get("broker", "unknown"),
                 "currency": "USD", "lots": [], "closed": []}
        if market.get("spot_usd"):
            entry["market"] = {"spot": market["spot_usd"],
                               "as_of": str(market.get("spot_date", old.get("as_of")))[:10]}
        for lot in position.get("lots", []):
            flags = []
            if lot.get("cb_review"):
                flags.append({"code": "cost_basis_unverified",
                              "note": lot["cb_review"], "raised_by": "migration"})
            new_lot = {
                "id": lot["id"], "broker": position.get("broker", "unknown"),
                "acq_date": str(lot["acq_date"])[:10], "qty": float(lot["qty"]),
                "cb_per_share": float(lot["cb_usd"]),
                "price_paid_per_share": float(lot.get("price_paid_usd", 0)),
                "acq_fx": float(lot["acq_fx"]), "funding": lot["funding"],
                "src": lot.get("src", f"migrated:{lot['id']}"),
                "confirmed": bool(lot.get("confirmed", False)),
            }
            if lot.get("origin"):
                new_lot["origin"] = lot["origin"]
            if lot.get("fifo_from"):
                new_lot["fifo_from"] = str(lot["fifo_from"])[:10]
            if flags:
                new_lot["flags"] = flags
            entry["lots"].append(new_lot)
        register["positions"][ticker] = entry

    print(f"{'DRY RUN — ' if args.dry_run else ''}migration from {src}")
    print(f"  positions {len(register['positions'])}")
    for ticker, entry in register["positions"].items():
        print(f"    {ticker}: {len(entry['lots'])} lots, "
              f"{'priced' if 'market' in entry else 'UNPRICED'}")
    print(f"  funding classes {len(register['funding'])}")
    print(f"\n  comment audit — {len(comments)} comment line(s) in holdings.yaml.")
    print("  ruamel.yaml is not a dependency here (research R-002), so comments")
    print("  do NOT round-trip. Anything load-bearing must already be a field:")
    for comment in comments[:12]:
        print(f"    {comment[:100]}")
    if len(comments) > 12:
        print(f"    ... and {len(comments) - 12} more")

    if args.dry_run:
        print("\nNothing written. Re-run without --dry-run to apply.")
        return 0

    errors = store.validate_against(register, "lot-register.schema.json",
                                    "migrated register")
    if errors:
        print(f"\nmigrated register does not satisfy its own schema "
              f"({len(errors)} problem(s)) — nothing written:", file=sys.stderr)
        for error in errors:
            print(f"  • {error}", file=sys.stderr)
        return 1

    target = store.save_yaml(REGISTER, register, REGISTER_HEADER)
    print(f"\nwrote {target}")
    print("  The vault is untouched. Verify with `report --format text` and "
          "compare against the vault program before trusting this (FR-057).")
    return 0


# ---------- dispatch ---------------------------------------------------------
def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="portfolio", description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("validate"); p.add_argument("--strict", action="store_true")
    p.set_defaults(func=cmd_validate)

    p = sub.add_parser("report")
    p.add_argument("--ticker"); p.add_argument("--as-of", dest="as_of")
    p.add_argument("--spot", type=float); p.add_argument("--fx", type=float)
    p.add_argument("--format", choices=["page", "json", "text"], default="page")
    p.set_defaults(func=cmd_report)

    p = sub.add_parser("import")
    p.add_argument("--file", required=True); p.add_argument("--profile", required=True)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--allow-duplicate-rows", action="store_true")
    p.set_defaults(func=cmd_import)

    p = sub.add_parser("share")
    p.add_argument("--profile", required=True); p.add_argument("--out")
    p.add_argument("--preview", action="store_true")
    p.set_defaults(func=cmd_share)

    p = sub.add_parser("migrate")
    p.add_argument("--from", dest="source", required=True)
    p.add_argument("--dry-run", action="store_true")
    p.set_defaults(func=cmd_migrate)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except DataError as exc:
        print(f"{exc}", file=sys.stderr)
        return 1
    except ValueError as exc:
        print(f"{exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
